### ISSUE TITLE
Problem building on OSX Yosemite

### ISSUE THREAD

**Issue by quintonparker** [Dridi/libvmod-named#1]
Hi

Me again. Doing things most normal people wouldn't do

Using OSX Yosemite as my dev env I can usually compile any/every VMOD but my trouble with this one is the following output when running make

> make
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /Users/quinton.parker/Downloads/libvmod-named/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/sh ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
vmodtool: /usr/local/Cellar/varnish/4.1.0/share/varnish/vmodtool.py vmod_named.vcc
WARNING: $Event description is not included in .rst:
[(68, '')]
Traceback (most recent call last):
  File "/usr/local/Cellar/varnish/4.1.0/share/varnish/vmodtool.py", line 976, in <module>
    runmain(i_vcc)
  File "/usr/local/Cellar/varnish/4.1.0/share/varnish/vmodtool.py", line 891, in runmain
    i.parse(vx)
  File "/usr/local/Cellar/varnish/4.1.0/share/varnish/vmodtool.py", line 785, in parse
    o = parse_obj(self)
  File "/usr/local/Cellar/varnish/4.1.0/share/varnish/vmodtool.py", line 710, in parse_obj
    f = parse_func(tl, "VOID")
  File "/usr/local/Cellar/varnish/4.1.0/share/varnish/vmodtool.py", line 695, in parse_func
    t = parse_arg(tl, al)
  File "/usr/local/Cellar/varnish/4.1.0/share/varnish/vmodtool.py", line 631, in parse_arg
    raise Exception("ARG? %s", t.str)
Exception: ('ARG? %s', 'ACL')
make[2]: *** [.vcc] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

I'm guessing this VMOD isn't intended to run on OSX?

**Comment by Dridi** [comment]
Hello @quintonparker,

Are you stalking me? :suspect:

This VMOD takes advantage of new features from Varnish 4.1.1 and 4.1.2, so `vmodtool` fails. I don't intend to support OSX if it's too much work, but first, please try to upgrade Varnish on your desktop. :smile:

Apologies for the complete lack of documentation, there are technical details (like the test suite that tends to only work on my machine) I want to deal with.

Dridi

**Comment by quintonparker** [comment]
Me stalk? NO. I'm just trying to install every VMOD I could possibly get my hands on because I know zilch about writing C code :smile: 

I tried that just now. Installed varnish 4.1.1 but I still get the same error output when running make

Not a train-smash if you can't help with this one. I can find other ways to get around the need for such a VMOD

**Comment by Dridi** [comment]
Read again, you need Varnish 4.1.2 ;)

I really take advantage of the latest stuff here!

**Comment by quintonparker** [comment]
Ah. Silly me. That worked. Feel free to close. Thanks again :+1:

**Comment by Dridi** [comment]
Thanks to you I know it builds on OSX, I'll try not to break that!
