### ISSUE TITLE
Issue running autogen.sh  

### ISSUE THREAD

**Issue by lcruzero** [Dridi/libvmod-named#2]
On CentOS6 running varnish 4.1.2-1 I'm getting an error when running ./autogen.sh :

 ./autogen.sh
+ aclocal -I m4 -I /usr/share/aclocal
+ libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
+ autoheader
+ automake --add-missing --copy --foreign
+ autoconf
configure.ac:44: error: possibly undefined macro: PKG_CHECK_VAR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

thanks.
-LC

**Comment by lcruzero** [comment]
centOS sys is running pkgconfig-0.23-9, adding pkg_check_var macro solved the issue. though I guess I could have just upgraded to pkgconfig-0.24

https://barnowl.mit.edu/browser/m4/pkg.m4

Add PKG_CHECK_VAR Macro to /usr/share/aclocal/pkg.m4:

# PKG_CHECK_VAR(VARIABLE, MODULE, CONFIG-VARIABLE,
# [ACTION-IF-FOUND], [ACTION-IF-NOT-FOUND])
# -------------------------------------------
# Retrieves the value of the pkg-config variable for the given module.
AC_DEFUN([PKG_CHECK_VAR],
[AC_REQUIRE([PKG_PROG_PKG_CONFIG])dnl
AC_ARG_VAR([$1], [value of $3 for $2, overriding pkg-config])dnl

_PKG_CONFIG([$1], [variable="][$3]["], [$2])
AS_VAR_COPY([$1], [pkg_cv_][$1])

AS_VAR_IF([$1], [""], [$5], [$4])dnl
])# PKG_CHECK_VAR

./autogen.sh

Install python-docutils

./configure


please close.

**Comment by Dridi** [comment]
Fixed in 2c3fe7b, thank you for reporting the bug.
