### ISSUE TITLE
Statistics about DNS failures (like dir_dns_failed in Varnish 3)

### ISSUE THREAD

**Issue by padan** [Dridi/libvmod-named#4]
Varnish 3.x had a statistics counter **dir_dns_failed** for failed DNS queries in the DNS Director.
Can something similar be implemented with Varnish 4.x + vmod named, so one can get some statistics or error counters about success or failure of the DNS lookups done by the module?

How can one detect or count DNS lookup errors when using vmod-named?

**Comment by Dridi** [comment]
Hello @padan,

> How can one detect or count DNS lookup errors when using vmod-named?

As we discussed outside of github, it is currently logged.

My response to you:
> You should at least see them with varnishlog, except that DNS
> resolution doesn't belong in any HTTP transaction. It is done
> asynchronously so you need to run `varnishlog -g raw` and look for
> records containing `vmod-named`.
>
> It should be documented in `man vmod_named` once installed:
> https://github.com/Dridi/libvmod-named/blob/2c3fe7b/src/vmod_named.vcc#L49-L61

Varnish counters (see `man varnish-counters`) are currently defined at compile-time in the Varnish source tree, so there's no way to define additional counters and AFAIK there are no plans to make it possible.

For that matter, I also mentioned this to you:
> I have other plans for status inspection, but they are currently
> stalling. However this counter would fit well in the status, so I'll
> keep you updated on github once I make progress.

I'm keeping track of the overall status question in #5.
