### ISSUE TITLE
Configurable backend cooling off

### ISSUE THREAD

**Issue by rnsanchez** [Dridi/libvmod-named#7]
We have a scenario where our server has 8620 backends, but only 462 are unique.  This can be alleviated by tweaking the (hard-coded) TTL, but it would be nice to have it configurable.  Plus, we would be able to change it on-the-fly, no restarts required.

As an example, we have backends for Amazon that cycle over IPv4s, since Amazon does not give us a list of addresses:

    ; <<>> DiG 9.10.4-P1 <<>> s3.amazon.com
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27427
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
    
    ;; QUESTION SECTION:
    ;s3.amazon.com.			IN	A
    
    ;; ANSWER SECTION:
    s3.amazon.com.		899	IN	CNAME	rewrite.amazon.com.
    rewrite.amazon.com.	59	IN	A	72.21.206.80
    
    ;; Query time: 470 msec
    ;; SERVER: 8.8.4.4#53(8.8.4.4)
    ;; WHEN: Fri Jul 08 16:30:19 BRT 2016
    ;; MSG SIZE  rcvd: 69
    
    
    ; <<>> DiG 9.10.4-P1 <<>> s3.amazon.com
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21466
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
    
    ;; QUESTION SECTION:
    ;s3.amazon.com.			IN	A
    
    ;; ANSWER SECTION:
    s3.amazon.com.		899	IN	CNAME	rewrite.amazon.com.
    rewrite.amazon.com.	59	IN	A	72.21.210.29
    
    ;; Query time: 607 msec
    ;; SERVER: 8.8.4.4#53(8.8.4.4)
    ;; WHEN: Fri Jul 08 16:31:29 BRT 2016
    ;; MSG SIZE  rcvd: 69
    
    
    ; <<>> DiG 9.10.4-P1 <<>> s3.amazon.com
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48721
    ;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
    
    ;; QUESTION SECTION:
    ;s3.amazon.com.			IN	A
    
    ;; ANSWER SECTION:
    s3.amazon.com.		829	IN	CNAME	rewrite.amazon.com.
    rewrite.amazon.com.	59	IN	A	72.21.206.80
    
    ;; Query time: 451 msec
    ;; SERVER: 8.8.4.4#53(8.8.4.4)
    ;; WHEN: Fri Jul 08 16:32:40 BRT 2016
    ;; MSG SIZE  rcvd: 69

**Comment by Dridi** [comment]
> We have a scenario where our server has 8620 backends, but only 462 are unique.

FWIW this module will only create distinct backends once if they belong to the same director. And as far as Varnish is concerned, TCP connection pools will be shared by backends with the same IP address (in the case of `vmod-named` it's always one address per backend).

Besides this issue, is your setup stable for that many backends?

> This can be alleviated by tweaking the (hard-coded) TTL, but it would be nice to have it configurable.

Please show me which TTL you are tweaking, there isn't much hard-coded in the current master branch.

**Comment by rnsanchez** [comment]
I just realized I misfiled this enhancement: the hardcoded value is on Varnish's side, and *not* libvmod-named.  Sorry for the noise.

```
/*--------------------------------------------------------------------
 * Delete a dynamic director::backend instance.  Undeleted dynamic and
 * static instances are GC'ed when the VCL is discarded (in cache_vcl.c)
 */

void
VRT_delete_backend(VRT_CTX, struct director **dp)
{
	struct director *d;
	struct backend *be;

	CHECK_OBJ_NOTNULL(ctx, VRT_CTX_MAGIC);
	AN(dp);
	d = *dp;
	*dp = NULL;
	CHECK_OBJ_NOTNULL(d, DIRECTOR_MAGIC);
	CAST_OBJ_NOTNULL(be, d->priv, BACKEND_MAGIC);
	Lck_Lock(&be->mtx);
	be->admin_health = vbe_ah_deleted;
	be->health_changed = VTIM_real();
	be->cooled = VTIM_real() + 60.; // <-- Here is the hard-coded cooldown...
	VTAILQ_REMOVE(&backends, be, list);
	VTAILQ_INSERT_TAIL(&cool_backends, be, list);
	Lck_Unlock(&be->mtx);

	// NB. The backend is still usable for the ongoing transactions,
	// this is why we don't bust the director's magic number.
}
```

**Comment by Dridi** [comment]
I'm well aware of this hard-coded value, I suspected it could be this one. Now I realize that I've been in touch with you on a related matter. I will probably follow whatever backend-related ticket closely :wink:
