### ISSUE TITLE
vmod doesn't work inside a docker container.

### ISSUE THREAD

**Issue by erickfaustino** [Dridi/libvmod-named#8]
Hi, @Dridi.
I'm using this VMOD, and it works fine, inside an EC2 host, but doesn't works when it's inside a docker container. I know that it's maybe out of the scope, but I just looking for help anyway, maybe you know the cause of the problem or just it's is expected.

I can see the name resolution working, inside varnishstat, varnish creates backends associated with IPs resolved, tcpdump shows me that is resolving names, but when I try one request, the connection opens and stills hanged. varnishlog, shows me some timeouts messages and nothing more else. Can you help to figure out this, please? If this is out of the scope of this vmod, just tell me, and I'll find another solution. 
Thanks anyway, one more time, this VMOD is amazing, just like the others you made.

**Comment by Dridi** [comment]
Hello @erickfaustino,

Thank you for your bug report, and I'm glad that this time I didn't break your production!

> I'm using this VMOD, and it works fine, inside an EC2 host

This is good news, it's one of this VMOD's goals :)

> but doesn't works when it's inside a docker container. I know that it's maybe out of the scope, but I just looking for help anyway, maybe you know the cause of the problem or just it's is expected.

No, it's supposed to work in containers too, there's no special treatment of any kind.

> Can you help to figure out this, please?

Sure, I'll give it a go soon, but it would help if you could share a minimal reproducer (eg. in the form of dockerfiles) to ease the task.

> Thanks anyway, one more time, this VMOD is amazing, just like the others you made.

Bribery doesn't work on me :p

**Comment by erickfaustino** [comment]
Hahaha. For the last part, I really think that, but I got it.
I will post a Dockerfile with a minimal setup, using vmod-named.
Thank you!

**Comment by erickfaustino** [comment]
Hi, @Dridi! I'm bringing good news. Your vmod works well with containers too, it was my mistake. When configuring a new named.director, needs to specify the host_header variable, and now, my setup is working. Thanks for responses and sorry for the misunderstood. If you want that I post the dockerfile anyway, let me know.
I'm closing this. Thank you one more time!

**Comment by Dridi** [comment]
Hi @erickfaustino,

This is good news but please show me how to reproduce it, I want to see it hang to understand the cause and either fix or document it. whichever is more appropriate.

As usual feel free to report anything wrong :)

Thanks,
Dridi

**Comment by erickfaustino** [comment]
Hey, @Dridi, Thanks for the fast reply. I'll post the dockerfile in another repository and show you how to reproduces it. 
Thank you!

Erick.

**Comment by Dridi** [comment]
I'm reopening this issue, waiting for the reproducer. Thanks again for reporting bugs!
